name: scan-and-publish

on:
  schedule:
    - cron: "0 * * * *"    # every hour (UTC)
  workflow_dispatch: {}     # manual Run button

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scanner (wider shortlist)
        run: |
          mkdir -p out_upload2
          python newcoin_hunter.py \
            --out out_upload2 \
            --target_disc 350 --target_ref 200 \
            --limit_per_chain 3000 \
            --max_age_h_refine 1200 \
            --min_traders_refine 2 \
            --min_vliq_refine 0.08 \
            --max_fdv_refine 30000000 \
            --min_lp_refine 3000 \
            --max_lp_refine 2000000 \
            --require_social_refine false

      - name: Prepare site folder
            - name: Stamp pages with build time
        run: |
          STAMP="<div style='padding:8px 12px;margin:12px 0;background:#fff9d6;border:1px solid #eee;font:14px system-ui'>
          Last updated: $(date -u '+%Y-%m-%d %H:%M:%S') UTC • Run ID: ${{ github.run_id }} • Commit: ${{ github.sha }}</div>"
          for f in site/index.html site/candidates_refined.html; do
            [ -f "$f" ] || continue
            python - "$f" "$STAMP" <<'PY'
import sys, io, re
p, stamp = sys.argv[1], sys.argv[2]
html = io.open(p, encoding="utf-8").read()
# insert after </h1> if present; else at top of <body>
if re.search(r"(?i)</h1>", html):
    html = re.sub(r"(?i)(</h1>)", r"\1\n"+stamp, html, count=1)
else:
    html = re.sub(r"(?i)<body[^>]*>", lambda m: m.group(0)+"\n"+stamp, html, count=1)
io.open(p, "w", encoding="utf-8").write(html)
PY
          done
        run: |
          mkdir -p site
          if [ -f out_upload2/candidates_discovery.html ]; then
            cp out_upload2/candidates_discovery.html site/index.html
          else
            echo "<h1>No discovery results</h1>" > site/index.html
          fi
          [ -f out_upload2/candidates_refined.html ] && cp out_upload2/candidates_refined.html site/candidates_refined.html || true
          [ -f out_upload2/candidates_refined.csv ] && cp out_upload2/candidates_refined.csv site/ || true
          [ -f out_upload2/candidates_discovery.csv ] && cp out_upload2/candidates_discovery.csv site/ || true
          [ -f out_upload2/rejects_refined.csv ] && cp out_upload2/rejects_refined.csv site/ || true
          [ -f out_upload2/rejects_discovery.csv ] && cp out_upload2/rejects_discovery.csv site/ || true

      - name: Upload artifact (for Pages)
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
